databases:
  - name: quizverse-db
    databaseName: quizverse
    user: quizverse_user

services:
  - type: web
    name: quizverse
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URI
        fromDatabase:
          name: quizverse-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true